### PR TITLE
Tutorials, take 2.5

### PR DESCRIPTION
**Pull request by timholy**
Redo of #38, this time from an easier-to-share branch.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
great :)

**Comment by SimonDanisch** [comment]
Thanks!

**Comment by timholy** [comment]
Sorry it took me a while to get back to this, and thanks for the contribution!

If it is important to control window initialization in such detail (for me, everything worked fine without it), perhaps it would be best to leverage GLWindow. I will look into a little bit of reorganization.

**Comment by SimonDanisch** [comment]
That's exactly the reason for GLWindow ;) GLWindow is a bit chaotic, but I at least added all the fixes needed over time...

**Pull request merged**
