### PR TITLE
Fixed calling sequences for "lift" according to new Reactive API (Rea…

### PR DESCRIPTION
**Pull request by AlainLich**
Hi,

needed to fix "lift" calling sequences when moving to latest Reactive master branch (of today)
Also fixed typing of several constants (Float64 -> Float32), since "lift" does not tackle this anymore.
Kept your change making Cameras mutable.

This solves a number of issues like:

```
ERROR: LoadError: LoadError: LoadError: MethodError: `lift` has no method matching lift(::Function, ::Type{FixedSizeArrays.Matrix4x4{Float32}}, ::Reactive.Lift{GLAbstraction.Pivot{Float32}})
Closest candidates are:
  lift(::Union(DataType,Function), !Matched::Reactive.Signal{T}...)
  lift(::Union(DataType,Function), !Matched::Reactive.SignalSource...)
 in call at /home/alain/.julia/v0.4/GLAbstraction/src/GLCamera.jl:328
 in call at /home/alain/.julia/v0.4/GLAbstraction/src/GLCamera.jl:235
 in createwindow at /home/alain/.julia/v0.4/GLWindow/src/reactglfw.jl:405
 in include at ./boot.jl:252
 in include_from_node1 at loading.jl:134
 in include_all at /home/alain/.julia/v0.4/Romeo/src/utils.jl:4
 in include at ./boot.jl:252
 in include_from_node1 at ./loading.jl:134
 in reload_path at ./loading.jl:158
 in _require at ./loading.jl:70
 in require at ./loading.jl:53
 in include at ./boot.jl:252
 in include_from_node1 at loading.jl:134
 in process_options at ./client.jl:310
 in _start at ./client.jl:409
while loading /home/alain/.julia/v0.4/Romeo/src/display/renderloop.jl, in expression starting on line 31
while loading /home/alain/.julia/v0.4/Romeo/src/Romeo.jl, in expression starting on line 45
while loading /home/alain/src/Julia/Romeo.jl/test/RomeoVolume.jl, in expression starting on line 3
```

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Great, haven't been on newest reactive master, so I guess that's why I haven't noticed this.
By the way, I just tested Romeo with GLVisualize. It seems to work fine, besides some things that I had to change in GLWindow. Give me some time to change a few things, so that it just works if you checkout GLVisualize.
Besides text and the edit function, everything should work (better even). 
GLVisualize basically replaces more or less the whole of Romeo. Now, only the more advanced GUI stuff can live in Romeo, and the more basic stuff can be shared between GLPlot and Romeo via GLVisualize.

**Comment by AlainLich** [comment]
OK, so **I will leave you time to make all of this happen**. Then I expect you tell me where
things are, between Romeo and GLVisualize. I will restart then the integration exercise.

Best
Alain

PS: Concerning **GLFW**      I was using `master` (commit on 5/7/15), and did not select or merge `julia04` since it has been around since  3/28/15. However I noticed that the changes in `julia04`
had not been merged in `master`. What do you recommend?

**Comment by SimonDanisch** [comment]
Do you have an example file, which should work after the switch? I could use that as a test, to see if everything runs as expected.

**Comment by SimonDanisch** [comment]
I just checked out reactive master and nothing seems to be broken...Can you give some details?
I'm not sure about the difference between master and julia04 in GLFW.... I cleaned some things up and introduced some other things without backward compatibility, so we didn't merge julia04 yet. @jayschwa is working on merging it bit by bit...

**Comment by AlainLich** [comment]
Hi,

not so simple:

* ) I am running Reactive:
```
 commit 7b822045feafa084a7f88a0030ff5d40a258e557
Merge: 7debb23 eada415
Author: Shashi Gowda <shashigowda91@gmail.com>
Date:   Thu May 7 14:46:17 2015 +0530
```

* You will find similar adaptations (*unrelated to Romeo/GLxxx*) to the new `lift` calling sequence in commit
```
commit 95c7a4526a6c1b49860b9535887d14e957f1a89e
Author: Shashi Gowda <shashigowda91@gmail.com>
Date:   Tue May 5 23:57:46 2015 +0530

    Fix tests after API change
```
where the diff is:
```
git diff 62324a60c11137147344c43c..95c7a4526a6c1b49860b95
diff --git a/test/basics.jl b/test/basics.jl
index 41e44d3..f240647 100644
--- a/test/basics.jl
+++ b/test/basics.jl
@@ -29,7 +29,7 @@ facts("Basic checks") do
         @fact b.value => a.value*a.value
 
         ## Multiple inputs to Lift
-        c = lift(+, Int, a, b)
+        c = lift(+, a, b, typ=Int)
         @fact c.value => a.value + b.value
 
         push!(a, number())
diff --git a/test/call_count.jl b/test/call_count.jl
index a733d4f..0ac486c 100644
--- a/test/call_count.jl
+++ b/test/call_count.jl
@@ -7,10 +7,10 @@ facts("Call counting") do
     a = Input(0)
     b = Input(0)
 
-    c = lift(+, Int, a, b)
+    c = lift(+, a, b)
     d = merge(a, b)
-    e = lift(+, Int, a, lift(x->2x, Int, a)) # Both depend on a
-    f = lift(+, Int, a, b, c, e)
+    e = lift(+, a, lift(x->2x, a)) # Both depend on a
+    f = lift(+, a, b, c, e)
 
     count = s -> foldl((x, y) -> x+1, 0, s)
```

* **Now the bad news**: I cannot give you a minimal working example since the failure occurs in
`using Romeo`. The only thing that happens is that once Reactive issues are fixed, I execute up to the next issue, this time related to **normalize**:

```
ERROR: LoadError: LoadError: LoadError: MethodError: `normalize` has no method matching normalize(::GeometryTypes.Vector3{Float32})
 in lookat at /home/alain/.julia/v0.4/GLAbstraction/src/GLMatrixMath.jl:146
 in call at /home/alain/.julia/v0.4/GLAbstraction/src/GLCamera.jl:335
 in call at /home/alain/.julia/v0.4/GLAbstraction/src/GLCamera.jl:235
 in createwindow at /home/alain/.julia/v0.4/GLWindow/src/reactglfw.jl:405
 in include at ./boot.jl:252
 in include_from_node1 at loading.jl:134
 in include_all at /home/alain/.julia/v0.4/Romeo/src/utils.jl:4
 in include at ./boot.jl:252
 in include_from_node1 at ./loading.jl:134
 in reload_path at ./loading.jl:158
 in _require at ./loading.jl:70
 in require at ./loading.jl:53
 in include at ./boot.jl:252
 in include_from_node1 at loading.jl:134
 in process_options at ./client.jl:310
 in _start at ./client.jl:409
while loading /home/alain/.julia/v0.4/Romeo/src/display/renderloop.jl, in expression starting on line 31
while loading /home/alain/.julia/v0.4/Romeo/src/Romeo.jl, in expression starting on line 45
while loading /home/alain/src/Julia/Romeo.jl/test/RomeoTestMicro.jl, in expression starting on line 7
```

Since I thought the best was not to bug you with new issues until you are through with Romeo,
we are stuck. I am not sure that the issue can be exhibited simply by `using GLWindow` (and I have not tried)

How to make progress: may be simply try resolve my current issue with `normalize` (which I had not looked into yet (will not happen before diner!)),and hope that `using Romeo` goes through.

**Comment by SimonDanisch** [comment]
Ah something went wrong with the checkout... Now I'm getting errors as well...
The normalize is really my problem, you're right, you shouldn't worry about it.. This is a one second fix for me... The problem is, that FixedSizeArrays and Quaternions both definde normalize... so I decided to rather let Quaternions.jl rely on FixedSizeArrays instead of the other way around, as Quaternions might be extended to use FixedSizeArrays.. but I got never around to create a pull request, because I thought it will get rejected...
I wanted a minimal example for trying out if your stuff will work with GLVisualize ;) It basically replaces all of Romeos functions, which have been in my master branch of Romeo...

**Comment by AlainLich** [comment]
Hi,

since I saw your message just now I have done the following:
* a) further patched GLAbstraction to resolve the "normalize" thing and change a couple more "lift" occurrences. This one I can send in a pull request. (id=patch2)
* b)  made some mods in Romeo.jl to import GeometryTypes and FixedSizeArrays. This is my
       branch `experimentN`
The net result is that the load of Romeo proceeds up to loading src/display where it **hangs** (so
this goes further than before but is far from ideal)

I have no minimal example of my stuff running since I cannot proceed with integration in the
current situation. Therefore, *I think that the easiest way is that you give me access to a working configuration with GLVisualize, so that I can integrate my stuff again in your new version*.

**Comment by SimonDanisch** [comment]
Well... The thing is just, I already did integrate things with my romeo example, but it's very simple so it doesn't necessarily work with yours ;)
You might have seen that I also updated quite a few things, and right now I'm building a little script, which checks out every packet to the right branch... This in the end should make things run for you!

**Comment by SimonDanisch** [comment]
Wow this script is insanely slow...
Well, but it should include all the packages on the right branch..
Sorry for the mess, but there is a lot of prototyping involved here^^
```Julia
!isa(Pkg.installed("GLWindow"), VersionNumber) && Pkg.add("GLWindow")
Pkg.checkout("GLWindow", "julia04")

!isa(Pkg.installed("GLAbstraction"), VersionNumber) && Pkg.add("GLAbstraction")
Pkg.checkout("GLAbstraction", "julia04")

!isa(Pkg.installed("ModernGL"), VersionNumber) && Pkg.add("ModernGL")
Pkg.checkout("ModernGL", "master")

!isa(Pkg.installed("FixedSizeArrays"), VersionNumber) && Pkg.clone("https://github.com/SimonDanisch/FixedSizeArrays.jl.git")
Pkg.checkout("FixedSizeArrays", "master")

!isa(Pkg.installed("GeometryTypes"), VersionNumber) && Pkg.clone("https://github.com/JuliaGeometry/GeometryTypes.jl.git")
Pkg.checkout("GeometryTypes", "master")

!isa(Pkg.installed("ColorTypes"), VersionNumber) && Pkg.clone("https://github.com/SimonDanisch/ColorTypes.jl.git")
Pkg.checkout("ColorTypes", "master")

!isa(Pkg.installed("Reactive"), VersionNumber) && Pkg.add("Reactive")
Pkg.checkout("Reactive", "master")

!isa(Pkg.installed("GLFW"), VersionNumber) && Pkg.add("GLFW")
Pkg.checkout("GLFW", "julia04")

!isa(Pkg.installed("Compat"), VersionNumber) && Pkg.add("Compat")
Pkg.checkout("Compat", "master")

!isa(Pkg.installed("ImageIO"), VersionNumber) && Pkg.clone("https://github.com/JuliaIO/ImageIO.jl.git")
Pkg.checkout("ImageIO", "master")


!isa(Pkg.installed("FileIO"), VersionNumber) && Pkg.clone("https://github.com/JuliaIO/FileIO.jl.git")
Pkg.checkout("FileIO", "master")

!isa(Pkg.installed("MeshIO"), VersionNumber) && Pkg.clone("https://github.com/JuliaIO/MeshIO.jl.git")
Pkg.checkout("MeshIO", "master")

!isa(Pkg.installed("Meshes"), VersionNumber) && Pkg.add("Meshes")
Pkg.checkout("Meshes", "meshes2.0")

!isa(Pkg.installed("AbstractGPUArray"), VersionNumber) && Pkg.clone("https://github.com/JuliaGPU/AbstractGPUArray.git")
Pkg.checkout("AbstractGPUArray", "master)
```

**Comment by AlainLich** [comment]
Hi,

**FYI**, my mods to src/Romeo.jl to load `GeometryTypes` and `FixedSizeArrays` (**RESULTING IN HANGING** WHEN including `src/display` appear on `https://github.com/AlainLich/Romeo.jl/commit/0099e670ed680feda9daec50be2cfe663bd78700`

The change log:
```
diff --git a/src/Romeo.jl b/src/Romeo.jl
index a49b466..5066ff2 100644
--- a/src/Romeo.jl
+++ b/src/Romeo.jl
@@ -2,6 +2,11 @@ module Romeo
 
 using GLWindow 
 using GLAbstraction
+             #Exists:methods(FixedSizeArrays.normalize)
+                 # 1 method for generic function "normalize":
+                 #  normalize{FSA<:FixedSizeArrays.FixedArray{T,NDim,SIZE}}(
+                 #       a::FSA<:FixedSizeArrays.FixedArray{T,NDim,SIZE})
+                 #       at /home/alain/.julia/v0.4/FixedSizeArrays/src/ops.jl:73
 using ModernGL
 using ImmutableArrays
 using Reactive
@@ -14,6 +19,12 @@ using Color
 using FixedPointNumbers
 import Mustache
 
+import GeometryTypes     #ADDED EXP using poses problems
+                         #Warning: both GeometryTypes and ImmutableArrays
+                         #         export "Vector3"; uses of it in module
+                         #         Main must be qualified
+using FixedSizeArrays   #ADDED EXP
+
 const sourcedir = Pkg.dir("Romeo", "src")
 const shaderdir = joinpath(sourcedir, "shader")
 
@@ -38,7 +49,8 @@ end
 Base.minimum{T, NDIM}(x::Array{Vector3{T},NDIM}) = reduce(minper, x)
 Base.maximum{T, NDIM}(x::Array{Vector3{T},NDIM}) = reduce(maxper, x)
 
-abstract AbstractFixedVector{T,C}   # had to add this (not found somewhere)
+abstract AbstractFixedVector{T,C}  #KEEP for now
+
```

**Comment by AlainLich** [comment]
Hi,

I have done all the Pkg checkouts conforming to your script. It does not say anything about GLVisualize though. Then tried a minimal example:
```
using Romeo, GLFW, GLAbstraction, Reactive, ModernGL, GLWindow, Color,
      ImmutableArrays

function mkVol(screen)
   npts3D = 12
   function plotFn3D(i,j,k)
         x = Float32(i)/Float32(npts3D)-0.5 
         y = Float32(j)/Float32(npts3D)-0.5 
         z = Float32(k)/Float32(npts3D)-0.5 

         ret = if ( x>=0 ) && ( x>=y)
                   2*x*x+3*y*y+z*z
               elseif ( x<0) 
                   2*sin(2.0*3.1416*x)*sin(3.0*3.1416*y)
               else
                   9*x*y*z
               end
          ret
   end
   visualize( Float32[ plotFn3D(i,j,k) for i=0:npts3D, 
                                   j=0:npts3D, k=0:npts3D ], screen=screen)
end

function mkSurf(screen)
    visualize(Float32[sin(i)sin(j) for i=0:0.1:5,
                                       j=0:0.1:5], primitive=SURFACE(),
                                       screen=screen)
end    

function setup(dovol)
    root_screen = Romeo.ROOT_SCREEN

    screenArea = lift(root_screen.area) do area
        Rectangle{Int}(0, 0, area.w, area.h)
    end 

    camera_inputs = root_screen.inputs
    camera_inputs[:window_size] = lift(x->Vector4(x.x, x.y, x.w, x.h), screenArea)
    # creates cameras for the sceen with the new inputs
    ocamera      = OrthographicPixelCamera(camera_inputs)
    pcamera      = PerspectiveCamera(camera_inputs, Vec3(2), Vec3(0))

    #call the ugly Screen constructor
    screen        = Screen(screenArea, root_screen, Screen[],
                           root_screen.inputs, RenderObject[],
                           root_screen.hidden, root_screen.hasfocus,
                           pcamera, ocamera, root_screen.nativewindow)
    push!(root_screen.children, screen)

    viz = dovol ?     mkVol(screen)    : mkSurf(screen)

    push!(screen.renderlist, viz)

end

# Select version
length(ARGS) <= 1 ? setup(true) : setup(false)

while Romeo.ROOT_SCREEN.inputs[:open].value
    glEnable(GL_SCISSOR_TEST)
    Romeo.renderloop(Romeo.ROOT_SCREEN)
    sleep(0.0001)
end

GLFW.Terminate()
```

This hangs; in more detail: it does open a window, allocate around 1Gbytes and hangs. Does
not respond to window being closed, has to be aborted. *Low CPU usage suggests waiting.*

Its stdout/stderr printout:
```
Warning: New definition 
    convert(Type{Images.Image{Cdest<:Union(Color.AbstractAlphaColorValue{C<:Color.ColorValue{T},T<:Real},Color.ColorValue{T}),N,A<:AbstractArray{T,N}}}, Images.AbstractImageDirect{Csrc<:Union(Color.AbstractAlphaColorValue{C<:Color.ColorValue{T},T<:Real},Color.ColorValue{T}),N}) at /home/alain/.julia/v0.4/Images/src/core.jl:229
is ambiguous with: 
    convert(Type{Images.Image{T,N,A<:AbstractArray{T,N}}}, Images.Image{T,N,A<:AbstractArray{T,N}}) at /home/alain/.julia/v0.4/Images/src/core.jl:202.
To fix, define 
    convert(Type{Images.Image{_<:Union(Color.AbstractAlphaColorValue{C<:Color.ColorValue{T},T<:Real},Color.ColorValue{T}),N,A<:AbstractArray{T,N}}}, Images.Image{_<:Union(Color.AbstractAlphaColorValue{C<:Color.ColorValue{T},T<:Real},Color.ColorValue{T}),N,A<:AbstractArray{T,N}})
before the new definition.
Warning: Method definition haskey(AbstractArray{T,N}, AbstractString) in module ImageIO at /home/alain/.julia/v0.4/ImageIO.jl/src/types.jl:114 overwritten in module Images at /home/alain/.julia/v0.4/Images/src/core.jl:616.
Warning: Method definition get(AbstractArray{T,N}, AbstractString, Any) in module ImageIO at /home/alain/.julia/v0.4/ImageIO.jl/src/types.jl:117 overwritten in module Images at /home/alain/.julia/v0.4/Images/src/core.jl:619.
WARNING: int(x::FloatingPoint) is deprecated, use round(Int,x) instead.
 in depwarn at ./deprecated.jl:42
 in int at deprecated.jl:31
 in anonymous at /home/alain/.julia/v0.4/Romeo/src/display/renderloop.jl:33
 in include at ./boot.jl:252
 in include_from_node1 at loading.jl:134
 in include_all at /home/alain/.julia/v0.4/Romeo/src/utils.jl:4
 in include at ./boot.jl:252
 in include_from_node1 at ./loading.jl:134
 in reload_path at ./loading.jl:158
 in _require at ./loading.jl:70
 in require at ./loading.jl:53
 in include at ./boot.jl:252
 in include_from_node1 at loading.jl:134
 in process_options at ./client.jl:310
 in _start at ./client.jl:409
```

Please send me a working example with **GLVisualize** (I suppose that this is the way to go). Then
I will need to know what is still active/valid in Romeo and what has been superseeded by GLVisualize. I guess that I will be able to clone `GLVisualize` from GitHub. 

Best
Alain

**Comment by SimonDanisch** [comment]
There are tons of example in GLVisualize/test folder ;)
And you're using Romeo, ImmutableArrays and Color, which has been replaced
by GLVisualize, GeometryTypes and ColorTypes ;) I haven't touched Romeo
yet, from now on it will be an empty shell, as GLVisualize does all the
rendering now. Well, an empty shell until I merge your stuff, which is way
more what Romeo should include.
I hope I can back port stuff, so that Color actually relies on ColorTypes
in the end. But that will need some work and testing, which I haven't been
willing to do yet.

2015-05-08 11:02 GMT+02:00 AlainLich <notifications@github.com>:

**Comment by AlainLich** [comment]
Hi,

I have loaded **GLVisualize**  and **several examples run** (NICE Graphics). I guess that this makes most of older Romeo redundant? *Is simplifying Romeo.jl so that it only loads my stuff and uses GLVisualize sufficient or is it more subtle?* 

Best
Alain

**Comment by SimonDanisch** [comment]
It should be something along these lines... I don't know any functionality
that hasn't been replaced... It's just, that it now has some more visuals,
but some parts are missing compared to Romeo. But it seems, that you're not
using them yet.
And I got rid of the visualize_interface and am dealing with defaults a
little different now. You can look into GLVisualize/visualize/* to see how
I deal with defaults now.
Are some examples not running? It seems, that the test_obj is not
running...I'm working on that right now

2015-05-08 12:13 GMT+02:00 AlainLich <notifications@github.com>:

**Comment by AlainLich** [comment]
Hi, I have not tried everything, so far:
```
NONWORKING = test_particles.jl
WORKING    = test_particles2D.jl runtests.jl test_romeo.jl
```
The next thing I do is try to make **src/Romeo.jl** skinny (remove redundant stuff) and try it in order to integrate my stuff.

**Comment by AlainLich** [comment]
Hi Simon, 
Done just that in my branch `skinny` at https://github.com/AlainLich/Romeo.jl/tree/skinny: skinned down Romeo tree and still working.
So far, I am able to draw 2D and 3D plots with simple minded program `RomeoTestMini.jl`. *Graphics
and mouse interaction seem better*.

My intent is to integrate XML functionality and only then package a pull request; however this might
only be done early next week ( week ends need not be rainy....)
Best
Alain

**Comment by SimonDanisch** [comment]
Really great =) I'm looking forward to this!

**Comment by SimonDanisch** [comment]
Hi Alain,
just wanted to notify, that I'm working on a better text display with cairo. I want to generalize that to render arbitrary shapes with cairo and the display them via opengl.
So in the end you could pre render glyphs, arrows, icons and whatnot with cairo and then display them efficiently with OpenGL.

Best,
Simon

**Comment by AlainLich** [comment]
Thanks for the information,
For the time being I am extending supported RenderObjects via XML, based on examples in GLVisualize. I
hope that things would have progressed by the end of the week end.

Best
Alain

**Comment by SimonDanisch** [comment]
Okay cool! 
Keep me updated! 
Ask me anything about RenderObjects that seems weird... They're probably not a great fit for your purpose, so instead of you tailoring your code to the ugliness of RenderObjects, we should probably rewrite them ;)
Actually, there should be really little code directly defined on the RenderObjects. RenderObjects are really just the end product of other stuff, which can be directly displayed via OpenGL.
Think of them as some method to cache the OpenGL drawing commands.

**Pull request merged**
