### PR TITLE
Clean up tutorials

### PR DESCRIPTION
**Pull request by timholy**
This extends the commits added by @SimonDanisch to cover all the tutorials.

I'm working on depth_stencils2, and there's sometihng that seems wrong about the rendering (as if the DEPTH buffer gets reset between RenderObjects), but I won't have any more time this morning to dig into it.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
>I'm working on depth_stencils2, and there's sometihng that seems wrong about the rendering (as if the DEPTH buffer gets reset between RenderObjects)

That's where I tricked you, with GLWindow... In the standard mode, it creates a framebuffer with the bare minimum, without depth buffer or stencil buffer.
I uploaded a fix!

**Comment by timholy** [comment]
Thanks! (Glad I asked!)

**Comment by SimonDanisch** [comment]
Yeah, don't hesitate to ask :) The probability is very high that I spot it with one look and save you some time ;)

**Comment by timholy** [comment]
OK, here are working depth & stencil tutorials.

I noticed a couple of code issues, of which one seems worth discussing. The `RenderObject`s use dictionaries, one for `prerender` and one for `postrender`. The actual `render` call seems like it is supposed to be in `postrenderobjects`. However, it is also tempting to add other things there: for example, say you want to call `glDepthMask(GL_FALSE)` for an object before rendering it, you might want to call `glDepthMask(GL_TRUE)` after it is rendered, and hence include this via `postrender!`. However, this isn't safe: dictionaries do not have a guaranteed iteration order, so if you do
```jl
postrender!(ro,
            render, ro.vertexarray, GL_TRIANGLES,
            glDepthMask, GL_TRUE)
```
then there is some possibility that the second function will run before the first. Worse, it will vary from run-to-run.

So, to me there seem to be a couple of possible options:
- use a `Vector{Pair{Function, Any}}`. This will guarantee order.
- split out the actual render call into its own step, so that all `postrender!` operations truly are "post-render."

**Comment by timholy** [comment]
I should also add that in `depth_stencils2.jl`, it doesn't work properly on my machine without the `glDisable(GL_STENCIL_TEST)` in the event loop. I'm puzzled by this, because I added this to the `prerender` tasks in `std_renderobject`.

**Comment by SimonDanisch** [comment]
That's exactly what i was talking about ;) I have a fix for that living in
sd/gpumap, or so... I'll look at it when i'm home!

**Comment by SimonDanisch** [comment]
Ah yeah, that's how I decided to implement it:
https://github.com/JuliaGL/GLAbstraction.jl/blob/gpumap/src/GLTypes.jl#L143
Might as well implement it with `find` instead of having the cluncy lookup dicts...
The `RenderObject` needs a thorough clean up anyways! It conflates many concepts and `render` is awfully slow!

**Comment by SimonDanisch** [comment]
I added the `glDisable(GL_STENCIL_TEST)` to the cube object, since that's (sadly) the way how you need to do it in GLAbstraction. It's a trade-off for a bit more performance. This way I can reduce the state changes a tiny bit. As already mentioned, the perfect solution would be to write an optimizer to sort the objects in a way that reduces state changes (So you would only give the `RenderObject` the states you need and the optimizer would decide what to enable and disable at what point).

**Comment by timholy** [comment]
I'm guessing you used a Dict because you want the user to be able to go back and "edit" the settings. If you switch to `find`, one other issue to think about: you might have both `glEnable(GL_DEPTH_TEST)` and `glEnable(GL_STENCIL_TEST)`; one cannot substitute for the other, so making the function as the "key" (whether for a Dict or using `find`) doesn't work in general.

**Comment by timholy** [comment]
Oh, and thanks for all the fixes. OK to merge? (I'm close to the end of these; I'll do the framebuffers, but not today, and then probably quit for a while.)

**Comment by SimonDanisch** [comment]
Yup looks good :) Thanks a lot!

**Pull request merged**
