### PR TITLE
fix #24

### LINKED ISSUE #24: Seg Fault on 64 bit Debian Jessie
I was trying to track down a segfault in GLVisualize and an identical one occurred in the tests for this package. I will update as I get more details, but I am curious if this is reproducible on other systems.

```
steve:~/.julia/v0.4/GLAbstraction(master)$ julia ./test/runtests.jl 

signal (11): Segmentation fault
glfwShowWindow at /home/steve/.julia/v0.4/GLFW/deps/usr64/lib/libglfw.so (unknown line)
ShowWindow at /home/steve/.julia/v0.4/GLFW/src/glfw3.jl:395
jlcall_ShowWindow_21548 at  (unknown line)
jl_apply_generic at /home/steve/Software/julia4/usr/bin/../lib/libjulia.so (unknown line)
anonymous at /home/steve/.julia/v0.4/GLAbstraction/test/runtests.jl:24
unknown function (ip: 0x7f599d92584b)
unknown function (ip: 0x7f599d92646c)
jl_load at /home/steve/Software/julia4/usr/bin/../lib/libjulia.so (unknown line)
include at ./boot.jl:261
jl_apply_generic at /home/steve/Software/julia4/usr/bin/../lib/libjulia.so (unknown line)
include_from_node1 at ./loading.jl:304
jl_apply_generic at /home/steve/Software/julia4/usr/bin/../lib/libjulia.so (unknown line)
process_options at ./client.jl:316
_start at ./client.jl:411
unknown function (ip: 0x7f599ac21129)
jl_apply_generic at /home/steve/Software/julia4/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: 0x401a37)
unknown function (ip: 0x40163f)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x401685)
unknown function (ip: (nil))
Segmentation fault
```

```
Julia Version 0.4.1-pre+8
Commit 1bb7e10 (2015-10-10 07:57 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

### PR DESCRIPTION
**Pull request by sjkelly**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
The core profie gave you a segfault?!?!

**Comment by sjkelly** [comment]
When this line is set:
```
GLFW.WindowHint(GLFW.CONTEXT_VERSION_MINOR, 0)
``` 
it works fine. If it is set to 3, it does not work. So both `CONTEXT_VERSION_MINOR` needs to be 0 and  `GLFW.OPENGL_PROFILE` needs to be unspecified. I discovered this by eliminating all window hints (which worked fine) then adding them back to find the suspect ones. I have not done enough research to understand what is really going on here, but .[SO](http://stackoverflow.com/questions/27790502/glfwcreatewindow-causes-a-segfault) mentions this can be cause by querying OpenGL without creating a context. https://github.com/JuliaGL/GLFW.jl/tree/dev might also have some progress to address this as well.

**Comment by sjkelly** [comment]
I think this might be due to it needing to be `OPENGL_COMPAT_PROFILE` rather than `OPENGL_CORE_PROFILE`. http://www.glfw.org/docs/latest/window.html#window_title

**Comment by Gnimuc** [comment]
@sjkelly i'm sure this change will break MacOS.  try using something like:
```
@osx ? (
    begin
        GLFW.WindowHint(GLFW.CONTEXT_VERSION_MAJOR, 3)
        GLFW.WindowHint(GLFW.CONTEXT_VERSION_MINOR, 3)
        GLFW.WindowHint(GLFW.OPENGL_PROFILE, GLFW.OPENGL_CORE_PROFILE)
        GLFW.WindowHint(GLFW.OPENGL_FORWARD_COMPAT, GL_TRUE)
    end
  : begin
        GLFW.DefaultWindowHints()
    end
)
```

**Comment by SimonDanisch** [comment]
@Gnimuc is right... But I was running into problems with the solution @Gnimuc proposes, since core profile behaves quite differently, but I was never testing it since I don't have mac os. Also, the OpenGL version seems to be higher on Ubuntu when initialized like on mac os.
So I decided to make the core profile the default.
I think we need to research this more... It can't be that core profile gives a segfault instead of an error message, so this must be a bug somewhere.

**Comment by Gnimuc** [comment]
@SimonDanisch It seems OSX is going to get stuck on OpenGL 4.1, this is [OpenGL Capabilities Tables](https://developer.apple.com/opengl/capabilities) for OSX. AFAIK, OSX only has 3 ModernGL profiles: 3.2, 3.3 and 4.1. When using GLFW, a simple way is to use the highest supported OpenGL version is to use `GLFW.DefaultWindowHints()`(the [document](http://www.glfw.org/docs/latest/window.html#window_hints_values) here is not clear) on Windows or Linux. but on OSX, `GLFW.DefaultWindowHints()` won't use ModernGL, it'll use 2.1 instead. It's from this that we should init OpenGL explicitly and carefully on OSX. 

I encountered a similar problem(I forgot whether it was a segfault) on an old machine which only support OpenGL 3.2, so I suspect that sjkelly forgot to upgrade graphic driver.

**Comment by SimonDanisch** [comment]
@Gnimuc Yeah I know... That's why I made the OSX initialization the default for all platforms, to make OpenGL behave as uniform as possible across platforms ;)

**Comment by SimonDanisch** [comment]
That's why I hope that we can find a better fix than @sjkelly proposed!

**Comment by sjkelly** [comment]
Yes, my graphics driver is most likely old. I am on SandyBridge which can handle 3.3, but mesa shows 3.0. I will keep digging for a more proper fix (OS-level or in GLFW init), but I'd like to keep this open in case someone re-discovers this issue. In the meantime I will use this locally so I can continue my OpenGL explorations in Julia :)

**Comment by Gnimuc** [comment]
>to make OpenGL behave as uniform as possible across platforms

Agreed! I get the point now:ok_hand: 

For my part, I prefer using the highest GL version when initializing GLFW and then doing version check later, for example:
````
renderer = bytestring(glGetString(GL_RENDERER))
@assert parse(Float32, version[1:3]) >= 3.2 "some error"
```
but yes this will introduce some uncertainties.

Currently, I suggest to add the message below to the README of all corresponding projects that are using ModernGL.jl.

>There are no dependencies, besides the graphic driver. If you have any problems, you should consider updating the driver first.

**Comment by sjkelly** [comment]
Closed in favor of #31

**Pull request closed without merging**
